# SPDX-License-Identifier: GPL-2.0
# Compiler flags, which are necessary to build userspace applications with the
# in-kernel libc "nolibc".

ifeq ($(and $(CONFIG_ARCH_HAS_NOLIBC),$(CONFIG_HEADERS_INSTALL)),y)

NOLIBC_USERCFLAGS := -nostdlib -nostdinc -static -ffreestanding \
		     -fno-asynchronous-unwind-tables -fno-stack-protector \
		     -isystem $(objtree)/usr/include -isystem $(srctree)/tools/include/nolibc/

NOLIBC_USERLDFLAGS := -nostdlib -nostdinc -static

endif # CONFIG_ARCH_HAS_NOLIBC && CONFIG_HEADERS_INSTALL
