# UAPI Header export list

generic-y += kvm_para.h
generic-y += shmparam.h
generic-y += siginfo.h
generic-y += swab.h
generic-y += timex.h

generic-y += errno.h
generic-y += fcntl.h
generic-y += ipcbuf.h
generic-y += msgbuf.h
generic-y += poll.h
generic-y += sembuf.h
generic-y += shmbuf.h

# no header-y since we need special user headers handling
# see arch/lkl/script/headers.py
