/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_NOMMU_SWMMU_H
#define _UAPI_LINUX_NOMMU_SWMMU_H

#define NOMMU_SWMMU_ACCESS_CHECKED	0U
#define NOMMU_SWMMU_ACCESS_SIGNAL	(1U << 0)

#define NOMMU_SWMMU_ACCESS_MASK	NOMMU_SWMMU_ACCESS_SIGNAL

#endif /* _UAPI_LINUX_NOMMU_SWMMU_H */
